title: Renxi's Homepage
page-top-title: Renxi Cheng
top-section-bg-text: Always thinking there must be an echo.
home-subtitle: Renxi Cheng (程仁熙)
copyright-text: '&copy; Renxi Cheng 2024-2027. All Rights Reserved.'
